# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-03 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_urls',
            field=models.TextField(default=datetime.datetime(2017, 6, 3, 8, 38, 53, 322440, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='quote',
            field=models.CharField(default=datetime.datetime(2017, 6, 3, 8, 39, 2, 238240, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
